import Mathlib

/-!
# High-dimensional differential topology and homotopy spheres: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is
`README.md`. The declarations below pin the principal colimits, geometric cycles, equivalence
relations, and quotients. An arbitrary `AddCommGrpCat` with the desired computed value does not
meet these signatures.
-/

namespace TauCetiRoadmap.HomotopySpheres

open CategoryTheory ContinuousMap
open CategoryTheory.Limits
open scoped ContDiff Manifold Topology

universe u v

/-! ## Convenient spaces and literal colimits -/

/-- Mapping spaces, loop spaces, and topological colimits use Mathlib's explicitly
universe-indexed category of compactly generated spaces. -/
abbrev ConvenientSpace := CompactlyGenerated.{u, u}

#check CompactlyGenerated.compactlyGeneratedToTop

/-- The suspension diagram whose `r`th object is the relevant unstable sphere homotopy group. -/
noncomputable def stableStemDiagram (k : ℕ) : ℕ ⥤ AddCommGrpCat := by
  sorry

/-- The `k`th stable stem is the literal colimit of suspension. -/
noncomputable def stableStem (k : ℕ) : AddCommGrpCat :=
  colimit (stableStemDiagram k)

/-- The canonical map from an unstable representative to the stable stem. -/
noncomputable def stableStemι (k r : ℕ) :
    (stableStemDiagram k).obj r ⟶ stableStem k :=
  colimit.ι (stableStemDiagram k) r

/-- The colimit universal property is part of the public API. -/
noncomputable def stableStemIsColimit (k : ℕ) :
    IsColimit (colimit.cocone (stableStemDiagram k)) :=
  colimit.isColimit (stableStemDiagram k)

/-- The block-inclusion diagram defining stable homotopy of `SO`. -/
noncomputable def stableSOHomotopyDiagram (k : ℕ) : ℕ ⥤ AddCommGrpCat := by
  sorry

noncomputable def stableSOHomotopy (k : ℕ) : AddCommGrpCat :=
  colimit (stableSOHomotopyDiagram k)

/-- Stable `J`, induced by the compatible finite orthogonal actions on spheres. -/
noncomputable def stableJ (k : ℕ) : stableSOHomotopy k ⟶ stableStem k := by
  sorry

/-- These are consequences of the full Bott cycle, not isolated inputs. -/
theorem stableSOHomotopy_five_subsingleton : Subsingleton (stableSOHomotopy 5) := by
  sorry

theorem stableSOHomotopy_six_subsingleton : Subsingleton (stableSOHomotopy 6) := by
  sorry

/-! ## A small smooth-manifold skeleton -/

private abbrev ModelSpace (n : ℕ) := EuclideanSpace ℝ (Fin n)

private noncomputable abbrev SmoothModel (n : ℕ) :=
  modelWithCornersSelf ℝ (ModelSpace n)

private abbrev Sphere (n : ℕ) :=
  Metric.sphere (0 : EuclideanSpace ℝ (Fin (n + 1))) 1

/-- A finite atlas code. It is small because its charts and transition maps live on the fixed
Type-0 model space. The implementation adds the exact cover, inverse, and cocycle laws. -/
structure SmoothAtlasCode (n : ℕ) where
  chartCount : ℕ
  chart : Fin chartCount → OpenPartialHomeomorph (ModelSpace n) (ModelSpace n)
  transition : Fin chartCount → Fin chartCount →
    OpenPartialHomeomorph (ModelSpace n) (ModelSpace n)
  transition_mem_groupoid :
    ∀ i j, transition i j ∈ contDiffGroupoid ∞ (SmoothModel n)

/-- Points in the disjoint union of chart domains before imposing transitions. -/
def SmoothAtlasCode.PrePoint {n : ℕ} (C : SmoothAtlasCode n) :=
  Σ i, (C.chart i).source

/-- The relation generated by the coded transition maps. -/
noncomputable def SmoothAtlasCode.gluingSetoid {n : ℕ} (C : SmoothAtlasCode n) :
    Setoid C.PrePoint := by
  sorry

/-- Realization is the actual quotient of the finite atlas code. -/
def SmoothAtlasCode.Realization {n : ℕ} (C : SmoothAtlasCode n) :=
  Quotient C.gluingSetoid

noncomputable instance {n : ℕ} (C : SmoothAtlasCode n) :
    TopologicalSpace C.Realization := by
  sorry

noncomputable instance {n : ℕ} (C : SmoothAtlasCode n) :
    ChartedSpace (ModelSpace n) C.Realization := by
  sorry

/-- A closed oriented cycle on the small atlas skeleton. The fields are genuine manifold and
topology conditions on the quotient realization, not asserted group calculations. -/
structure SmoothClosedOrientedCycle (n : ℕ) where
  code : SmoothAtlasCode n
  t2 : T2Space code.Realization
  secondCountable : SecondCountableTopology code.Realization
  compact : CompactSpace code.Realization
  manifold : IsManifold (SmoothModel n) ∞ code.Realization
  orientationAt : code.Realization →
    _root_.Orientation ℝ (ModelSpace n) (Fin n)

attribute [instance] SmoothClosedOrientedCycle.t2
  SmoothClosedOrientedCycle.secondCountable SmoothClosedOrientedCycle.compact
  SmoothClosedOrientedCycle.manifold

/-- Every compact second-countable smooth manifold has a representative in the small skeleton.
The proof uses the finite triangulation/handle supplier and retains an actual diffeomorphism. -/
noncomputable def smoothClosedOrientedCycleCode
    (n : ℕ) (M : Type u) [TopologicalSpace M] [T2Space M]
    [SecondCountableTopology M] [CompactSpace M]
    [ChartedSpace (ModelSpace n) M] [IsManifold (SmoothModel n) ∞ M]
    (oM : M → _root_.Orientation ℝ (ModelSpace n) (Fin n)) :
    {C : SmoothClosedOrientedCycle n //
      Nonempty (M ≃ₘ⟮SmoothModel n, SmoothModel n⟯ C.code.Realization)} := by
  sorry

/-! ## Geometric cycle quotients -/

/-- A `Theta_n` cycle is a small oriented manifold code with a sphere marking. -/
structure HomotopySphereCycle (n : ℕ) extends SmoothClosedOrientedCycle n where
  marking : code.Realization ≃ₕ Sphere n

/-- The relation is oriented h-cobordism on the shared collared carrier. -/
noncomputable def HomotopySphereCycle.HCobordant (n : ℕ) :
    HomotopySphereCycle n → HomotopySphereCycle n → Prop := by
  sorry

theorem homotopySphere_hCobordant_equivalence (n : ℕ) :
    Equivalence (HomotopySphereCycle.HCobordant n) := by
  sorry

def HomotopySphereClass (n : ℕ) :=
  Quotient ⟨HomotopySphereCycle.HCobordant n,
    homotopySphere_hCobordant_equivalence n⟩

@[instance_reducible]
noncomputable def homotopySphereClassAddCommGroup (n : ℕ) (hn : 5 ≤ n) :
    AddCommGroup (HomotopySphereClass n) := by
  sorry

/-- `Theta_n` is definitionally the geometric h-cobordism quotient. -/
noncomputable def homotopySphereGroup (n : ℕ) (hn : 5 ≤ n) : AddCommGrpCat :=
  letI := homotopySphereClassAddCommGroup n hn
  AddCommGrpCat.of (HomotopySphereClass n)

/-- An arbitrary-universe homotopy sphere maps into the selected small group through its code. -/
noncomputable def homotopySphereClassOf
    (n : ℕ) (hn : 5 ≤ n) (M : Type u) [TopologicalSpace M] [T2Space M]
    [SecondCountableTopology M] [CompactSpace M]
    [ChartedSpace (ModelSpace n) M] [IsManifold (SmoothModel n) ∞ M]
    (oM : M → _root_.Orientation ℝ (ModelSpace n) (Fin n))
    (hM : M ≃ₕ Sphere n) : homotopySphereGroup n hn := by
  sorry

/-- A chosen stable tangent framing, including the stabilization rank. -/
structure StableTangentFraming (n : ℕ) (M : Type*) where
  rank : ℕ
  frameAt : M →
    (ModelSpace n × ModelSpace rank) ≃L[ℝ] ModelSpace (n + rank)

/-- An honest tangent framing. -/
structure TangentFraming (n : ℕ) (M : Type*) where
  frameAt : M → ModelSpace n ≃L[ℝ] ModelSpace n

noncomputable def TangentFraming.stabilize {n : ℕ} {M : Type*}
    (framing : TangentFraming n M) (rank : ℕ) : StableTangentFraming n M := by
  sorry

/-- A framed-bordism cycle uses any closed oriented manifold, not only a homotopy sphere. -/
structure FramedCycle (n : ℕ) extends SmoothClosedOrientedCycle n where
  framing : StableTangentFraming n code.Realization

noncomputable def FramedCycle.Bordant (n : ℕ) :
    FramedCycle n → FramedCycle n → Prop := by
  sorry

theorem framedBordant_equivalence (n : ℕ) :
    Equivalence (FramedCycle.Bordant n) := by
  sorry

def FramedBordismClass (n : ℕ) :=
  Quotient ⟨FramedCycle.Bordant n, framedBordant_equivalence n⟩

noncomputable instance framedBordismClassAddCommGroup (n : ℕ) :
    AddCommGroup (FramedBordismClass n) := by
  sorry

noncomputable def framedBordismGroup (n : ℕ) : AddCommGrpCat :=
  AddCommGrpCat.of (FramedBordismClass n)

/-- Pontryagin--Thom after proving the corrected Thom-space factorization and regular-value
inverse. -/
noncomputable def pontryaginThom (n : ℕ) : framedBordismGroup n ≅ stableStem n := by
  sorry

/-- A representative collapse factorization. For rank `k`, the middle target is the Thom space
`Σ^k M_+`; only the augmentation has target `S^k`. -/
structure PontryaginThomFactorization (n k : ℕ) where
  cycle : FramedCycle n
  thomSpace : Type
  [thomTopology : TopologicalSpace thomSpace]
  collapse : Sphere (n + k) → thomSpace
  augmentation : thomSpace → Sphere k
  thomEquivSuspendedBase :
    Nonempty (thomSpace ≃ₜ OnePoint (cycle.code.Realization × ModelSpace k))

/-- A geometric almost-framed cycle exposes its defect disc and framing off it. -/
structure AlmostFramedCycle (n : ℕ) extends SmoothClosedOrientedCycle n where
  defect : Set code.Realization
  defectHomeomorph : defect ≃ₜ Metric.closedBall (0 : ModelSpace n) 1
  frameRank : ℕ
  frameOffDefect : {x : code.Realization // x ∉ defect} →
    (ModelSpace n × ModelSpace frameRank) ≃L[ℝ] ModelSpace (n + frameRank)

noncomputable def AlmostFramedCycle.Bordant (n : ℕ) :
    AlmostFramedCycle n → AlmostFramedCycle n → Prop := by
  sorry

theorem almostFramedBordant_equivalence (n : ℕ) :
    Equivalence (AlmostFramedCycle.Bordant n) := by
  sorry

def AlmostFramedBordismClass (n : ℕ) :=
  Quotient ⟨AlmostFramedCycle.Bordant n, almostFramedBordant_equivalence n⟩

noncomputable instance almostFramedBordismClassAddCommGroup (n : ℕ) :
    AddCommGroup (AlmostFramedBordismClass n) := by
  sorry

noncomputable def almostFramedBordismGroup (n : ℕ) : AddCommGrpCat :=
  AddCommGrpCat.of (AlmostFramedBordismClass n)

/-- A filling remains named stably framed until destabilization supplies an honest framing. -/
structure StableFramedFillingCycle (n : ℕ) where
  code : SmoothAtlasCode n
  boundaryCode : SmoothAtlasCode (n - 1)
  boundaryMarking : boundaryCode.Realization ≃ₕ Sphere (n - 1)
  stableFraming : StableTangentFraming n code.Realization

noncomputable def StableFramedFillingCycle.Bordant (n : ℕ) :
    StableFramedFillingCycle n → StableFramedFillingCycle n → Prop := by
  sorry

theorem stableFramedFillingBordant_equivalence (n : ℕ) :
    Equivalence (StableFramedFillingCycle.Bordant n) := by
  sorry

def StableFramedFillingClass (n : ℕ) :=
  Quotient ⟨StableFramedFillingCycle.Bordant n,
    stableFramedFillingBordant_equivalence n⟩

@[instance_reducible]
noncomputable def stableFramedFillingClassAddCommGroup (n : ℕ) (hn : 5 ≤ n) :
    AddCommGroup (StableFramedFillingClass n) := by
  sorry

noncomputable def stableFramedFillingGroup (n : ℕ) (hn : 5 ≤ n) : AddCommGrpCat :=
  letI := stableFramedFillingClassAddCommGroup n hn
  AddCommGrpCat.of (StableFramedFillingClass n)

/-! ## Historical carriers and Wall parity -/

/-- The historical `A_n` cycle retains its top cell and stable normal framing. -/
structure HistoricalAlmostParallelizableCycle (n : ℕ)
    extends SmoothClosedOrientedCycle n where
  topCell : Set code.Realization
  normalFrameRank : ℕ
  stableNormalFrameOffTopCell : {x : code.Realization // x ∉ topCell} →
    (ModelSpace n × ModelSpace normalFrameRank) ≃L[ℝ]
      ModelSpace (n + normalFrameRank)

/-- The historical `P_n` cycle has an honest framing. -/
structure HistoricalParallelizableFillingCycle (n : ℕ)
    extends StableFramedFillingCycle n where
  honestFraming : TangentFraming n code.Realization

/-- The chosen honest framing stabilizes to the original stable framing through a homotopy fixed
on the boundary collar. This is deliberately weaker than equality of framing data. -/
noncomputable def StableFramedFillingCycle.StabilizesRelBoundary
    {n : ℕ} (W : StableFramedFillingCycle n)
    (honest : TangentFraming n W.code.Realization) : Prop := by
  sorry

/-- The exact stable-to-honest cancellation conclusion for compact connected fillings with
nonempty boundary, relative to the collar encoded by the implementation. -/
theorem stableFraming_destabilizes (n : ℕ) (hn : 6 ≤ n)
    (W : StableFramedFillingCycle n) :
    ∃ honest : TangentFraming n W.code.Realization,
      W.StabilizesRelBoundary honest := by
  sorry

noncomputable def historicalAlmostParallelizableSetoid (n : ℕ) :
    Setoid (HistoricalAlmostParallelizableCycle n) := by
  sorry

noncomputable def historicalParallelizableFillingSetoid (n : ℕ) :
    Setoid (HistoricalParallelizableFillingCycle n) := by
  sorry

def HistoricalAlmostParallelizableClass (n : ℕ) :=
  Quotient (historicalAlmostParallelizableSetoid n)

def HistoricalParallelizableFillingClass (n : ℕ) :=
  Quotient (historicalParallelizableFillingSetoid n)

noncomputable instance historicalAlmostParallelizableClassAddCommGroup (n : ℕ) :
    AddCommGroup (HistoricalAlmostParallelizableClass n) := by
  sorry

@[instance_reducible]
noncomputable def historicalParallelizableFillingClassAddCommGroup
    (n : ℕ) (hn : 5 ≤ n) :
    AddCommGroup (HistoricalParallelizableFillingClass n) := by
  sorry

noncomputable def historicalAlmostParallelizableGroup (n : ℕ) : AddCommGrpCat :=
  AddCommGrpCat.of (HistoricalAlmostParallelizableClass n)

noncomputable def historicalParallelizableFillingGroup (n : ℕ) (hn : 5 ≤ n) :
    AddCommGrpCat :=
  letI := historicalParallelizableFillingClassAddCommGroup n hn
  AddCommGrpCat.of (HistoricalParallelizableFillingClass n)

/-- The convenient and historical `A_n` carriers are compared by an explicit group isomorphism. -/
noncomputable def almostFramedIsoHistorical (n : ℕ) :
    almostFramedBordismGroup n ≅ historicalAlmostParallelizableGroup n := by
  sorry

/-- The convenient stable filling and historical honest `P_n` carriers are explicitly compared. -/
noncomputable def stableFillingIsoHistorical (n : ℕ) (hn : 6 ≤ n) :
    stableFramedFillingGroup n (by omega) ≅
      historicalParallelizableFillingGroup n (by omega) := by
  sorry

noncomputable def almostFramedToHistorical (n : ℕ) :
    almostFramedBordismGroup n ⟶ historicalAlmostParallelizableGroup n :=
  (almostFramedIsoHistorical n).hom

noncomputable def historicalToAlmostFramed (n : ℕ) :
    historicalAlmostParallelizableGroup n ⟶ almostFramedBordismGroup n :=
  (almostFramedIsoHistorical n).inv

theorem almostFramed_historical_inverse (n : ℕ) :
    almostFramedToHistorical n ≫ historicalToAlmostFramed n = 𝟙 _ := by
  simp [almostFramedToHistorical, historicalToAlmostFramed]

theorem historical_almostFramed_inverse (n : ℕ) :
    historicalToAlmostFramed n ≫ almostFramedToHistorical n = 𝟙 _ := by
  simp [almostFramedToHistorical, historicalToAlmostFramed]

noncomputable def stableFillingToHistorical (n : ℕ) (hn : 6 ≤ n) :
    stableFramedFillingGroup n (by omega) ⟶
      historicalParallelizableFillingGroup n (by omega) :=
  (stableFillingIsoHistorical n hn).hom

noncomputable def historicalToStableFilling (n : ℕ) (hn : 6 ≤ n) :
    historicalParallelizableFillingGroup n (by omega) ⟶
      stableFramedFillingGroup n (by omega) :=
  (stableFillingIsoHistorical n hn).inv

theorem stableFilling_historical_inverse (n : ℕ) (hn : 6 ≤ n) :
    stableFillingToHistorical n hn ≫ historicalToStableFilling n hn = 𝟙 _ := by
  simp [stableFillingToHistorical, historicalToStableFilling]

theorem historical_stableFilling_inverse (n : ℕ) (hn : 6 ≤ n) :
    historicalToStableFilling n hn ≫ stableFillingToHistorical n hn = 𝟙 _ := by
  simp [stableFillingToHistorical, historicalToStableFilling]

/-- Even-dimensional Wall data are finite integral matrices with a quadratic refinement. -/
structure EvenWallForm (q : ℕ) where
  rank : ℕ
  pairing : Matrix (Fin rank) (Fin rank) ℤ
  quadratic : Fin rank → ℤ
  unimodular : IsUnit pairing.det

/-- Odd-dimensional Wall data are formations, with two displayed lagrangian bases. -/
structure OddWallFormation (q : ℕ) where
  form : EvenWallForm q
  lagrangianRank : ℕ
  firstLagrangian : Matrix (Fin form.rank) (Fin lagrangianRank) ℤ
  secondLagrangian : Matrix (Fin form.rank) (Fin lagrangianRank) ℤ

/-- The obstruction carrier distinguishes even forms from odd formations by construction. -/
inductive WallSurgeryDatum : ℕ → Type
  | even (q : ℕ) : EvenWallForm q → WallSurgeryDatum (2 * q)
  | odd (q : ℕ) : OddWallFormation q → WallSurgeryDatum (2 * q + 1)

noncomputable def wallStableEquivalence (n : ℕ) :
    Setoid (WallSurgeryDatum n) := by
  sorry

def WallSurgeryClass (n : ℕ) := Quotient (wallStableEquivalence n)

noncomputable instance wallSurgeryClassAddCommGroup (n : ℕ) :
    AddCommGroup (WallSurgeryClass n) := by
  sorry

noncomputable def wallSurgeryObstructionGroup (n : ℕ) : AddCommGrpCat :=
  AddCommGrpCat.of (WallSurgeryClass n)

/-- Delete the defect-disc interior. -/
noncomputable def almostFramedToFilling (n : ℕ) (hn : 5 ≤ n) :
    almostFramedBordismGroup n ⟶ stableFramedFillingGroup n hn := by
  sorry

/-- The boundary map uses the actual boundary marking. -/
noncomputable def fillingBoundary (n : ℕ) (hn : 6 ≤ n) :
    stableFramedFillingGroup n (by omega) ⟶ homotopySphereGroup (n - 1) (by omega) := by
  sorry

/-- The historical defect map is obtained only after both carrier comparisons. -/
noncomputable def historicalAlmostFramedToFilling (n : ℕ) (hn : 6 ≤ n) :
    historicalAlmostParallelizableGroup n ⟶
      historicalParallelizableFillingGroup n (by omega) :=
  historicalToAlmostFramed n ≫ almostFramedToFilling n (by omega) ≫
    stableFillingToHistorical n hn

theorem almostFramedToFilling_comparison (n : ℕ) (hn : 6 ≤ n) :
    almostFramedToHistorical n ≫ historicalAlmostFramedToFilling n hn =
      almostFramedToFilling n (by omega) ≫ stableFillingToHistorical n hn := by
  simp [historicalAlmostFramedToFilling, almostFramedToHistorical,
    historicalToAlmostFramed]

/-- The historical boundary map is transported from the collared geometric boundary map. -/
noncomputable def historicalFillingBoundary (n : ℕ) (hn : 6 ≤ n) :
    historicalParallelizableFillingGroup n (by omega) ⟶
      homotopySphereGroup (n - 1) (by omega) :=
  historicalToStableFilling n hn ≫ fillingBoundary n hn

theorem fillingBoundary_comparison (n : ℕ) (hn : 6 ≤ n) :
    stableFillingToHistorical n hn ≫ historicalFillingBoundary n hn =
      fillingBoundary n hn := by
  simp [historicalFillingBoundary, stableFillingToHistorical,
    historicalToStableFilling]

/-! ## The normalized sixth-stem representative -/

/-- `ν²` is the stabilization of `ν₄ ∘ Σ³ν₄ : S¹⁰ → S⁴`. -/
noncomputable def nuSquared : stableStem 6 := by
  sorry

theorem two_nuSquared : 2 • nuSquared = 0 := by
  sorry

theorem nuSquared_ne_zero : nuSquared ≠ 0 := by
  sorry

noncomputable def sixthStableStemEquiv : stableStem 6 ≃+ ZMod 2 := by
  sorry

@[simp]
theorem sixthStableStemEquiv_nuSquared : sixthStableStemEquiv nuSquared = 1 := by
  sorry

/-- The framed regular-value cycle of the fixed unstable representative. -/
noncomputable def nuSquaredFramedCycle : FramedCycle 6 := by
  sorry

theorem nuSquaredFramedCycle_class :
    (pontryaginThom 6).hom (Quotient.mk _ nuSquaredFramedCycle) = nuSquared := by
  sorry

noncomputable def kervaireInvariantSix : stableStem 6 ⟶ AddCommGrpCat.of (ZMod 2) := by
  sorry

theorem kervaireInvariantSix_nuSquared : kervaireInvariantSix nuSquared = 1 := by
  sorry

/-! ## Exactness and oriented recognition -/

noncomputable def homotopySphereToAlmostFramed (n : ℕ) (hn : 5 ≤ n) :
    homotopySphereGroup n hn ⟶ almostFramedBordismGroup n := by
  sorry

noncomputable def homotopySphereToHistoricalAlmostFramed (n : ℕ) (hn : 5 ≤ n) :
    homotopySphereGroup n hn ⟶ historicalAlmostParallelizableGroup n :=
  homotopySphereToAlmostFramed n hn ≫ almostFramedToHistorical n

theorem homotopySphereToAlmostFramed_comparison (n : ℕ) (hn : 5 ≤ n) :
    homotopySphereToAlmostFramed n hn ≫ almostFramedToHistorical n =
      homotopySphereToHistoricalAlmostFramed n hn := rfl

theorem exact_homotopySphere_almostFramed_filling (n : ℕ) (hn : 6 ≤ n) :
    Function.Exact (homotopySphereToAlmostFramed n (by omega))
      (almostFramedToFilling n (by omega)) := by
  sorry

theorem homotopySphereGroup_six_subsingleton :
    Subsingleton (homotopySphereGroup 6 (by omega)) := by
  sorry

private abbrev SixSphere := Sphere 6

private noncomputable abbrev SixModel := SmoothModel 6

/-- A diffeomorphism together with the derivative equation expressing orientation preservation. -/
def OrientationPreservingDiffeomorph (M : Type u) (N : Type v) [TopologicalSpace M]
    [TopologicalSpace N] [ChartedSpace (ModelSpace 6) M] [ChartedSpace (ModelSpace 6) N]
    (oM : M → _root_.Orientation ℝ (ModelSpace 6) (Fin 6))
    (oN : N → _root_.Orientation ℝ (ModelSpace 6) (Fin 6)) :=
  {f : M ≃ₘ⟮SixModel, SixModel⟯ N // ∀ x,
    _root_.Orientation.map (Fin 6)
      (f.mfderivToContinuousLinearEquiv (by simp) x).toLinearEquiv (oM x) = oN (f x)}

/-- The orientation-preserving recognition theorem. The arguments are the pointwise views of the
orientations supplied by the shared `Manifold.Orientation` API. -/
theorem smoothPoincareSix_oriented (M : Type u) [TopologicalSpace M] [T2Space M]
    [SecondCountableTopology M] [CompactSpace M]
    [ChartedSpace (ModelSpace 6) M] [IsManifold SixModel ∞ M]
    (oM : M → _root_.Orientation ℝ (ModelSpace 6) (Fin 6))
    (oS : SixSphere → _root_.Orientation ℝ (ModelSpace 6) (Fin 6))
    (_h : M ≃ₕ SixSphere) :
    Nonempty (OrientationPreservingDiffeomorph M SixSphere oM oS) := by
  sorry

/-- Forgetting orientations recovers the ordinary recognition corollary. -/
theorem smoothPoincareSix (M : Type u) [TopologicalSpace M] [T2Space M]
    [SecondCountableTopology M] [CompactSpace M]
    [ChartedSpace (ModelSpace 6) M] [IsManifold SixModel ∞ M]
    (_h : M ≃ₕ SixSphere) :
    Nonempty (M ≃ₘ⟮SixModel, SixModel⟯ SixSphere) := by
  sorry

end TauCetiRoadmap.HomotopySpheres
